# .github/workflows/gh-pages.yml (최신 버전 예시)
name: Deploy Hugo site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - name: Install Hugo
        run: |
          HUGO_VER=0.125.6
          curl -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_linux-amd64.tar.gz \
          | tar -xz && sudo mv hugo /usr/local/bin/
      - name: Build with Hugo
        run: hugo --minify
      - uses: actions/upload-pages-artifact@v2   # ⬅︎ 여기
        with: { path: ./public }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v2
